name: Build & Release Extension

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "25"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Build & package extension
        run: npm run release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          files: ovoo-chrome-extension-v*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
